src/Entity/Client.php
<?php

namespace App\Entity;

use App\Entity\Intervention;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ClientRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: ClientRepository::class)]
#[UniqueEntity(fields: ["phone"], message: "Il existe déjà un client avec ce numéro")]
#[ORM\Table(name: "tbl_client")]
class Client
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: "integer")]
    private ?int $id = null;

    #[ORM\Column(type: "string", length: 255)]
    private ?string $last_name = null;

    #[ORM\Column(type: "string", length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(type: "string", length: 255)]
    private ?string $phone = null;

    #[ORM\Column(type: "string", length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(type: "string", length: 255, nullable: true)]
    private ?string $street = null;

    #[ORM\Column(type: "string", length: 255, nullable: true)]
    private ?string $city = null;

    #[ORM\Column(type: "string", length: 255, nullable: true)]
    private ?string $postalCode = null;

    #[ORM\OneToMany(targetEntity: Intervention::class, mappedBy: "client")]
    private Collection $interventions;

    public function __construct()
    {
        $this->interventions = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->last_name . ' ' . $this->first_name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;
        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;
        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;
        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;
        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(?string $street): self
    {
        $this->street = $street;
        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;
        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    public function setPostalCode(?string $postalCode): self
    {
        $this->postalCode = $postalCode;
        return $this;
    }

    /**
     * @return Collection|Intervention[]
     */
    public function getInterventions(): Collection
    {
        return $this->interventions;
    }

    public function addIntervention(Intervention $intervention): self
    {
        if (!$this->interventions->contains($intervention)) {
            $this->interventions[] = $intervention;
            $intervention->setClient($this);
        }
        return $this;
    }

    public function removeIntervention(Intervention $intervention): self
    {
        if ($this->interventions->contains($intervention)) {
            $this->interventions->removeElement($intervention);
            if ($intervention->getClient() === $this) {
                $intervention->setClient(null);
            }
        }
        return $this;
    }
}

src/Entity/Intervention.php
<?php

namespace App\Entity;

use App\Entity\Task;
use App\Entity\User;
use App\Entity\Prop;
use App\Entity\Client;
use DateTimeInterface;
use App\Entity\Equipment;
use App\Entity\BillingLine;
use Doctrine\DBAL\Types\Types;
use App\Entity\OperatingSystem;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\InterventionReport;
use App\Repository\InterventionRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: InterventionRepository::class)]
#[ORM\Table(name: "tbl_intervention")]
class Intervention
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: "datetime")]
    private DateTimeInterface $deposit_date;

    #[ORM\Column(type: "datetime", nullable: true)]
    private ?\DateTimeInterface $return_date = null;

    #[ORM\Column(type: "text", nullable: true)]
    private ?string $comment = null;

    #[ORM\ManyToOne(targetEntity: OperatingSystem::class, inversedBy: "interventions")]
    #[ORM\JoinColumn(nullable: false)]
    private ?OperatingSystem $operating_system = null;

    #[ORM\ManyToOne(targetEntity: Equipment::class, inversedBy: "interventions")]
    #[ORM\JoinColumn(nullable: false)]
    private ?Equipment $equipment = null;

    #[ORM\ManyToMany(targetEntity: Prop::class, inversedBy: "interventions")]
    #[ORM\JoinTable(name: "intervention_prop")]
    private Collection $props;

    #[ORM\ManyToMany(targetEntity: Task::class, inversedBy: "interventions")]
    private Collection $tasks;

    #[ORM\ManyToOne(targetEntity: Client::class, inversedBy: "interventions")]
    #[ORM\JoinColumn(nullable: false)]
    private ?Client $client = null;

    #[ORM\Column(type: "string", length: 255)]
    private string $status;

    #[ORM\OneToOne(targetEntity: InterventionReport::class, inversedBy: "intervention", cascade: ["persist", "remove"])]
    #[ORM\JoinColumn(nullable: false)]
    private InterventionReport $intervention_report;

    #[ORM\Column(type: "string", length: 255)]
    private string $total_price;

    #[ORM\OneToMany(targetEntity: BillingLine::class, mappedBy: "intervention")]
    private Collection $billing_lines;

    #[ORM\ManyToOne(inversedBy: 'intervention')]
    private ?User $user = null;

    // #[ORM\ManyToOne(targetEntity: User::class, inversedBy: "interventions")]
    // #[ORM\JoinColumn(nullable: true)]
    // private ?User $user = null;

    public function __construct()
    {
        $this->tasks = new ArrayCollection();
        $this->props = new ArrayCollection();
        $this->setDepositDate(new \DateTime());
        $this->setStatus('En attente');
        $this->billing_lines = new ArrayCollection();
    }    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDepositDate(): \DateTimeInterface
    {
        return $this->deposit_date;
    }

    public function setDepositDate(\DateTimeInterface $deposit_date): self
    {
        $this->deposit_date = $deposit_date;
        return $this;
    }

    public function getReturnDate(): ?\DateTimeInterface
    {
        return $this->return_date;
    }

    public function setReturnDate(?\DateTimeInterface $return_date): self
    {
        $this->return_date = $return_date;
        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;
        return $this;
    }

    public function getOperatingSystem(): ?OperatingSystem
    {
        return $this->operating_system;
    }

    public function setOperatingSystem(?OperatingSystem $operating_system): self
    {
        $this->operating_system = $operating_system;
        return $this;
    }

    public function getEquipment(): ?Equipment
    {
        return $this->equipment;
    }

    public function setEquipment(?Equipment $equipment): self
    {
        $this->equipment = $equipment;
        return $this;
    }

    public function getTasks(): Collection
    {
        return $this->tasks;
    }

    public function addTask(Task $task): self
    {
        if (!$this->tasks->contains($task)) {
            $this->tasks[] = $task;
        }
        return $this;
    }

    public function removeTask(Task $task): self
    {
        if ($this->tasks->contains($task)) {
            $this->tasks->removeElement($task);
        }
        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;
        return $this;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;
        return $this;
    }

    public function getInterventionReport(): InterventionReport
    {
        return $this->intervention_report;
    }

    public function setInterventionReport(InterventionReport $intervention_report): self
    {
        $this->intervention_report = $intervention_report;
        return $this;
    }

    public function getTotalPrice(): string
    {
        return $this->total_price;
    }

    public function setTotalPrice(string $total_price): self
    {
        $this->total_price = $total_price;
        return $this;
    }

    public function getBillingLines(): Collection
    {
        return $this->billing_lines;
    }

    public function addBillingLine(BillingLine $billingLine): self
    {
        if (!$this->billing_lines->contains($billingLine)) {
            $this->billing_lines[] = $billingLine;
            $billingLine->setIntervention($this);
        }
        return $this;
    }

    public function removeBillingLine(BillingLine $billingLine): self
    {
        if ($this->billing_lines->contains($billingLine)) {
            $this->billing_lines->removeElement($billingLine);
            if ($billingLine->getIntervention() === $this) {
                $billingLine->setIntervention(null);
            }
        }
        return $this;
    }

    // public function getUser(): ?User
    // {
    //     return $this->user;
    // }

    // public function setUser(?User $user): self
    // {
    //     $this->user = $user;
    //     return $this;
    // }


    public function getProps(): Collection
    {
        return $this->props;
    }

    public function addProp(Prop $prop): self
    {
        if (!$this->props->contains($prop)) {
            $this->props[] = $prop;
        }
        return $this;
    }
    
    public function removeProp(Prop $prop): self
    {
        if ($this->props->contains($prop)) {
            $this->props->removeElement($prop);
        }
        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/ClientType.php
<?php

namespace App\Form;

use App\Entity\Client;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('last_name')
            ->add('first_name')
            ->add('phone')
            ->add('email')
            ->add('street')
            ->add('city')
            ->add('postal_code')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Client::class,
        ]);
    }
}

src/Controller/ClientController.php
<?php

namespace App\Controller;


use App\Entity\Client;
use App\Form\ClientType;
use App\Repository\ClientRepository;
use App\Repository\InterventionRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/client')]
class ClientController extends AbstractController
{
    #[Route("/", name: "client_index", methods: ["GET"])]
    public function index(ClientRepository $clientRepository): Response
    {
        return $this->render('client/index.html.twig', [
            'clients' => $clientRepository->findAll(),
        ]);
    }

    #[Route("/new", name: "client_new", methods: ["GET","POST"])]
    public function new(Request $request): Response
    {


        $client = new Client();
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($client);
            $entityManager->flush();

            if ($request->query->get('s') === 'intervention') {
                // Rediriger vers /intervention/new?client-id=5
                return $this->redirectToRoute('intervention_new', ['client-id' => $client->getId()]);
            }
            

            return $this->redirectToRoute('client_show', [
                'id' => $client->getId(),
            ]);
        }

        return $this->render('client/new.html.twig', [
            'client' => $client,
            'form' => $form->createView(),
        ]);
    }

    #[Route("/{id}", name: "client_show", methods: ["GET"])]
    public function show(Client $client, InterventionRepository $interventionRepository): Response
    {
        $interventions = $interventionRepository->findAllByClient($client->getId());

        return $this->render('client/show.html.twig', [
            'client' => $client,
            'interventions' => $interventions,
        ]);
    }

    #[Route("/{id}/edit", name: "client_edit", methods: ["GET","POST"])]
    public function edit(Request $request, Client $client): Response
    {
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('client_show', [
                'id' => $client->getId(),
            ]);
        }

        return $this->render('client/edit.html.twig', [
            'client' => $client,
            'form' => $form->createView(),
        ]);
    }

    #[Route("/{id}", name: "client_delete", methods: ["DELETE"])]
    public function delete(Request $request, Client $client): Response
    {
        if ($this->isCsrfTokenValid('delete'.$client->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($client);
            $entityManager->flush();
        }

        return $this->redirectToRoute('client_index');
    }
}

templates/client/_delete_form.html.twig
<form method="post" action="{{ path('client_delete', {'id': client.id}) }}" onsubmit="return confirm('Voulez-vous vraiment supprimer ce client ?');" class='d-inline'>
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ client.id) }}">
    <button class="red-btn f-20 px-4 py-2">Supprimer</button>
</form>

templates/client/_form.html.twig
{{ form_start(form) }}

    <div class="p-4 form container-background">
        <div class="container">
            <div class="row justify-content-md-center">
                <div class='col-6'>
                    <div class='col row'>
                        <h5>Nom</h5>            
                        {{ form_errors(form.last_name) }}
                        {{ form_widget(form.last_name, {'attr': {'class': 'mb-3'}}) }}
                    </div>

                    <div class='col row'>
                        <h5>Prénom</h5>            
                        {{ form_errors(form.first_name) }}
                        {{ form_widget(form.first_name, {'attr': {'class': 'mb-3'}}) }}
                    </div>

                    <div class='col row'>
                        <h5>Téléphone</h5>
                        {{ form_errors(form.phone) }}
                        {{ form_widget(form.phone, {'attr': {'class': 'mb-3'}}) }}
                    </div>

                    <div class='col row'>
                        <h5>Email <span class='h6 font-italic'>(facultatif)<span></h5>
                        {{ form_errors(form.email) }}
                        {{ form_widget(form.email, {'attr': {'class': 'mb-3'}}) }}
                    </div>
                </div>

                <div class='col-6'>
                    <div class='col row'>
                        <h5>Adresse <span class='h6 font-italic'>(facultatif)<span></h5>            
                        {{ form_errors(form.street) }}
                        {{ form_widget(form.street, {'attr': {'class': 'mb-3'}}) }}
                    </div>

                    <div class='col row'>
                        <h5>Ville <span class='h6 font-italic'>(facultatif)<span></h5>            
                        {{ form_errors(form.city) }}
                        {{ form_widget(form.city, {'attr': {'class': 'mb-3'}}) }}
                    </div>

                    <div class='col row'>
                        <h5>Code postal <span class='h6 font-italic'>(facultatif)<span></h5>            
                        {{ form_errors(form.postal_code) }}
                        {{ form_widget(form.postal_code, {'attr': {'class': 'mb-3'}}) }}
                    </div>
                </div>

                <button class="green-btn py-2 px-4 mt-3">{{ button_label|default('Valider') }}</button>
            </div>
        </div>
    </div>

{{ form_end(form) }}

templates/client/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier la fiche client{% endblock %}

{% block body %}
    <a href="{{ path('client_show', {'id': client.id}) }}"><i class="fas fa-chevron-left h1 float-left"></i></a>
    <h2 class='text-center mb-5 font-weight-bold'>Modifier la fiche client</h2>

    {{ include('client/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
{% endblock %}

templates/client/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des clients{% endblock %}

{% block javascripts %}        
    <script src="{{ asset('assets/js/searchBar.js') }}"></script>
{% endblock %}

{% block body %}
    <div class='text-center mb-2'>	
        <div class='h2 mb-3 font-weight-bold'>Liste des clients</div>
    </div>
    <div class='text-center mb-2'>	
        <a href='{{ path('client_new') }}'><input type='button' value="Ajouter une fiche client" class='grey-btn f-20 py-2 px-4' /></a>
    </div>

    <hr>

    <input class='w-100 mb-3 p-2' type="text" id="searchBar" placeholder="Rechercher un client">

    <div class='container list'>
        <div class="row tab-head p-2">
            <div class="col-3">Nom</div>
            <div class="col-3">Prénom</div>
            <div class="col-2">Phone</div>
            <div class="col-4">Email</div>
        </div>

        {% for client in clients %}
            <a class='data-row' href="{{ path('client_show', {'id': client.id}) }}">
                <div class="row link default p-2">
                    <div class="col-3 my-auto">{{ client.lastName }}</div>
                    <div class="col-3 my-auto">{{ client.firstName }}</div>
                    <div class="col-2 my-auto">{{ client.phone }}</div>
                    <div class="col-4 my-auto">{{ client.email ?: "<div class='missing-info'>Non-renseignée</div>" }}</div>
                </div>
            </a>
        {% else %}
            <div class="row">
                <div class='col text-center alert-label p-2'>Aucun clients enregistrés</div>
            </div>
        {% endfor %}
        
    </div>
{% endblock %}

templates/client/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle fiche client{% endblock %}

{% block body %}
    <a href="{{ path('client_index') }}"><i class="fas fa-chevron-left h1 float-left"></i></a>
    <h2 class='text-center mb-5 font-weight-bold'>Nouvelle fiche client</h2>

    {{ include('client/_form.html.twig') }}
{% endblock %}

templates/client/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion de la fiche client{% endblock %}

{% block body %}
    <div class='text-center'>	
        <div class='h2 mb-3 font-weight-bold'>Gestion de la fiche client</div>
        <a class="grey-btn f-20 px-4 py-2" href="{{ path('client_edit', {'id': client.id}) }}">Modifier</a>
        {{ include('client/_delete_form.html.twig') }}
    </div>
    <hr>

    <div class="container show-container">
        <div class="row justify-content-around">
            <div class="container-background col-md-auto mb-auto mr-5 p-4">
                <div class='f-20 text-center font-weight-bold'>Le client</div>
                <hr>
                <div class='row mb-2'>
                    <div class='col-md-auto my-auto'><i class="fas fa-user"></i></div>
                    <div class='col'>{{ client.lastName }} {{ client.firstName }}</div>
                </div>
                <hr>
                <div class='row mb-2'>
                    <div class='col-md-auto my-auto'><i class="fas fa-phone"></i></div>
                    <div class='col'>{{ client.phone }}</div>
                </div>
                <hr>
                <div class='row mb-2'>
                    <div class='col-md-auto my-auto'><i class="fas fa-at"></i></div>
                    <div class='col'>{{ client.email ?: "<div class='missing-info'>Email non-renseignée</div>" }}</div>
                </div>
                <hr>
                <div class='row'>
                    <div class='col-md-auto my-auto'><i class="fas fa-map-marker-alt"></i></div>
                    <div class='col'>
                        <div class="d-flex flex-column">
                            {% if (client.street) or (client.city) or (client.postalCode) %}
                                {% if client.street %}
                                    <div>{{ client.street }}</div>
                                {% endif %}
                                {% if (client.city) or (client.postalCode) %}
                                    <div>{{ client.city }} {{ client.postalCode }}</div>
                                {% endif %}
                            {% else %}
                                <div class='missing-info'>Adresse non-renseignée</div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>



            <div class="container-background list col mb-auto p-4">
                <div class='f-20 text-center font-weight-bold'>Liste des demandes d'interventions de {{ client }}</div>
                <hr>
                <div class='container'>
                    <div class="row py-2 tab-head">
                        <div class="col-2">Ouverture</div>
                        <div class="col-2">Equipement</div>
                        <div class="col-4">Techniciens</div>
                        <div class="col-4">Tâches</div>
                    </div>
                    {% for intervention in interventions %}
                        <a href="{{ path('intervention_show', {'id': intervention.id}) }}">
                            <div class="row link py-1">
                                <div class="col-2 my-auto">{{ intervention.depositDate ? intervention.depositDate|date('d-m-Y') : '' }}</div>
                                <div class="col-2 my-auto">{{ intervention.equipment }}</div>
                                <div class="col-4 my-auto">{% for technician in intervention.interventionReport.technicians %}{{ technician }}{% if not loop.last %}, {% endif %}{% endfor %}</div>
                                <div class="col-4 my-auto">{% for task in intervention.tasks %}{{ task }}{% if not loop.last %}, {% endif %}{% endfor %}</div>
                            </div>
                        </a>
                    {% else %}
                        <div class="row">
                            <div class='col text-center p-2'>Aucunes demandes d'interventions enregistrées</div>
                        </div>
                    {% endfor %}
                <div>
            </div>
        </div>
    </div>
{% endblock %}